/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#89ceff",
        "surface": "#101415",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-highest": "#323537",
        "on-secondary-fixed": "#111c2d",
        "surface-bright": "#363a3b",
        "primary-fixed": "#c9e6ff",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-high": "#272a2c",
        "on-background": "#e0e3e5",
        "on-surface-variant": "#bec8d2",
        "outline": "#88929b",
        "surface-variant": "#323537",
        "tertiary": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "inverse-on-surface": "#2d3133",
        "on-surface": "#e0e3e5",
        "on-primary-fixed-variant": "#004c6e",
        "surface-container-low": "#191c1e",
        "on-tertiary": "#213145",
        "outline-variant": "#3e4850",
        "surface-dim": "#101415",
        "on-primary": "#00344d",
        "on-primary-fixed": "#001e2f",
        "surface-container": "#1d2022",
        "on-tertiary-container": "#243449",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-lowest": "#0b0f10",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary": "#263143",
        "inverse-primary": "#006591",
        "tertiary-container": "#8d9db5",
        "background": "#101415",
        "inverse-surface": "#e0e3e5",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#b7c8e1",
        "secondary-container": "#3e495d",
        "surface-tint": "#89ceff",
        "on-error-container": "#ffdad6",
        "secondary": "#bcc7de",
        "on-primary-container": "#003751",
        "primary": "#89ceff",
        "on-secondary-container": "#aeb9d0",
        "primary-container": "#003751",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-padding": "120px",
        "container-max": "1200px",
        "card-padding": "24px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "code-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
}
